# Generated by Django 4.2.11 on 2024-03-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='nombre',
        ),
    ]
