# Generated by Django 4.2.11 on 2024-03-27 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='destino',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.destino'),
            preserve_default=False,
        ),
    ]
