# Generated by Django 4.2.11 on 2024-03-28 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_album_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino_dificultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Destino_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.destino'),
        ),
        migrations.AddField(
            model_name='destino',
            name='dificultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.destino_dificultad'),
        ),
        migrations.AddField(
            model_name='destino',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.destino_tipo'),
        ),
    ]
