# Generated by Django 4.2.11 on 2024-03-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_destino_dificultad_destino_tipo_alter_album_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='duracion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='autor',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='destino_dificultad',
            name='dificultad',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='destino_tipo',
            name='tipo',
            field=models.CharField(max_length=64),
        ),
    ]
