# Generated by Django 4.2.11 on 2024-03-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_destino_desnivel_destino_distancia_destino_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(0, 'Deshabilitado'), (1, 'Habilitado')], null=True),
        ),
    ]
