# Generated by Django 4.2.11 on 2024-03-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_destino_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='posicion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
