# Generated by Django 4.2.11 on 2024-03-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_destino_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=64)),
                ('localidad', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='destino',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.despartamento'),
        ),
    ]
